spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chess?serverTimezone=UTC&characterEncoding=UTF-8
    password: password
    username: user

  h2:
    console:
      enabled: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
